# This is the first real CI workflow in the course.
# It verifies a change by running tests on a fresh runner.
name: 02 CI Workflow

on:
  # Run automatically when app code, tests, or this workflow file changes.
  push:
    paths: # trigger when push on these pathes 
      - "app/**"
      - "tests/**"
      - ".github/workflows/02-ci.yml"
  # Allow a safe manual run before students trigger it with a code change.
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
    # The runner is the temporary machine that executes the steps below.
  run-tests:
    

    strategy: # this create multiple parallel jobs upon on its values 
      fail-fast: false # this check if you want if happen failure in pipeline fail full pipeline or continiure
      matrix:
        python-version: ["3.11", "3.12"]
        os : [ubuntu-latest, macos-latest]

    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}


    steps:
      - name: Check out repository # name of the step
        # Download the repository contents onto the runner.
        uses: actions/checkout@v6 # use this actions to clone the repo inside the vm
        # it will clone code from repo of that .yml file on it to inside vm 
      - name: validate code is cloned 
        run: |
          ls -R # list the files in the repo


        
      # - name: Set up Python
      #   # Prepare Python on the runner. This does not change the student laptop.
      #   env :
      #     PYTHON_VERSION: "3.12"
      #   uses: actions/setup-python@v6
      #   with:
      #     # python-version: ${{env.PYTHON_VERSION}}
      #     python-version: ${{ secrets.PYTHON_VERSION }}

      - name: Set up Python2
        # Prepare Python on the runner. This does not change the student laptop.
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

          
      - name : validate python is installed 
        run : |
          python --version
      - name: Run tests
        # This is the key verification step in the CI workflow.
        run: python -m unittest discover -s tests -v
      - name : get runner time 
        run : date